version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: sena-pj
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-vol: